DirectoryPath: "dist"
EnforceHTTPS: false
IgnoreURLs:
  - "/api/*"
CheckLinks: true
CheckImages: false
CheckScripts: false
CheckGeneric: false
CheckExternal: false
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreDirectoryMissingTrailingSlash: true
