name = "network-interconnect"
type = "webpack"
workers_dev = true
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/network-interconnect*"
kv_namespaces = [ 
  { binding = "REDIRECTS", id = "3f3c2364bfc349ea9ff511b935b0a2ad" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
