---
# Warning: cloudflare.BrandNames
#
# Suggests correct spelling and capitalization for brand names.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/

extends: substitution
message: "**Warning**: Use correct brand name: '%s' instead of '%s'."
level: warning
ignorecase: false
swap:
  (?<!https?:\/\/[^\s]*)(?<!create-)(?!Cloudflare)(?:[cC]loud[fF]lare)): Cloudflare
  (?<!https?:\/\/[^\s]*)(?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS]): cdnjs
  (?<!https?:\/\/[^\s]*)(?!GitHub)(?:[gG]it\s?[hH]ub): GitHub
  (?<!https?:\/\/[^\s]*)(?!GitLab)(?:[gG]it\s?[lL]ab): GitLab
  (?<!https?:\/\/[^\s]*)(?!Next\.js)(?:[nN][eE][xX][tT][\s\.]?[jJ[sS]): Next.js
