---
# Warning: cloudflare.BrandNames
#
# Suggests correct spelling and capitalization for brand names.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/

extends: substitution
message: "**Warning**: Use correct brand name: '%s' instead of '%s'."
level: warning
ignorecase: false
swap:
  (?<=^|\s)(?!Cloudflare)(?:[cC]loud[fF]lare)(?='s|\s|$): Cloudflare
  (?<=^|\s)(?!cdnjs)(?:[cC][dD][nN]\.?[jJ][sS])(?='s|\s|$): cdnjs
  (?<=^|\s)(?!GitHub)(?:[gG]it\s?[hH]ub)(?='s|\s|$): GitHub
  (?<=^|\s)(?!GitLab)(?:[gG]it\s?[lL]ab)(?='s|\s|$): GitLab
