---
# Warning: cloudflare.MeaningfulLinkWords
#
# Checks for the presence of semantically unhelpful words in link text.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/
extends: existence
message: "**Warning**: Rewrite the link text for `%s` to be more descriptive.


\n\n\nFor more information, refer to [Descriptive link text](https://developers.cloudflare.com/style-guide/formatting/structure/links/#descriptive-link-text)."
level: warning
ignorecase: true
scope: raw
nonword: true
tokens:
  - \[here\]\(.*\)
  - \[this page\]\(.*\)
  - \[read more\]\(.*\)

