---
# Error: cloudflare.RelativeLinks
#
# Checks for the presence of absolute hyperlinks that should be relative.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/
extends: existence
message: "**Error**: When referring another page our docs, use a relative link (`/1.1.1.1/`) instead of the full URL (`https://developers.cloudflare.com/1.1.1.1/`)."
level: error
scope: raw
raw:
  - '\[.+\]\(https?:\/\/developers\.cloudflare\.com\/.+\)'
