---
# Error: cloudflare.Repetition
#
# Checks for duplicate words, like `the the` or `and and`.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/
extends: repetition
message: "**Warning**: Remove this duplicate word: '%s'."
level: warning
alpha: true
tokens:
  - '[^\s]+'
