---
# Warning: cloudflare.UnclearAntecedent
#
# Checks for words that need a noun for clarity.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/
extends: existence
message: "**Warning**: Instead of '%s', try starting this sentence with a specific subject and verb."
level: warning
ignorecase: false
tokens:
  - 'That is'
  - 'That was'
  - 'These are'
  - 'These were'
  - 'There are'
  - 'There were'
  - 'This is'
  - 'This was'
  - 'Those are'
  - 'Those were'
