version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    commit-message:
      prefix: "[Docs Site] "
    schedule:
      interval: "weekly"
      day: "tuesday"
    assignees:
      - "kodster28"
    reviewers:
      - "cloudflare/content-engineering"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
