name = "bots"
type = "webpack"
workers_dev = true
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
# Opt into backwards-incompatible changes through September 17, 2021.
compatibility_date = "2021-09-17"

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/bots*"
kv_namespaces = [
    { binding = "REDIRECTS", id = "8851304780a744369049e4612d5b7132" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
