stages:
  - review
  - deploy

default:
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://vault.cfdata.org

include:
  - component: $CI_SERVER_FQDN/cloudflare/ci/ai/opencode@~latest
    inputs:
      runOnMR: true
  - component: $CI_SERVER_FQDN/$COMPONENT_1
