// Generated by Wrangler on Tue Sep 17 2024 00:57:27 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types -c wrangler-workers.toml --experimental-include-runtime`

interface Env {
	API_DOCS_KV: KVNamespace;
	ASSETS: Fetcher;
}
declare module "*/_redirects" {
	const value: string;
	export default value;
}
