// Generated by Wrangler by running `wrangler types -c wrangler-workers.toml --experimental-include-runtime`

interface Env {
	API_DOCS_KV: KVNamespace;
	ASSETS: Fetcher;
}
declare module "*/_redirects" {
	const value: string;
	export default value;
}