name = "cloudflare-docs"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
compatibility_date = "2022-09-27"
main = "./worker/index.ts"

rules = [
	{ type = "Text", globs = ["**/_redirects"], fallthrough = true },
]

[experimental_assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "API_DOCS_KV"
id = "77919060ee0444caa5113f5866b047df"
