#:schema ./node_modules/wrangler/config-schema.json
name = "cloudflare-docs"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
compatibility_date = "2024-10-14"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.ts"

workers_dev = true
route = { pattern = "developers.cloudflare.com/*", zone_name = "developers.cloudflare.com"}

rules = [
	{ type = "Text", globs = ["**/_redirects"], fallthrough = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "API_DOCS_KV"
id = "77919060ee0444caa5113f5866b047df"
