import type { AgentData } from "./types";

export const AGENTS: AgentData[] = [
	{
		name: "Claude Code",
		vendor: "Anthropic",
		slug: "claude-code",
		icon: "claude",
		description:
			"Coding agent available in the terminal, Claude desktop app, and supported editors. It understands your codebase, runs commands, and edits files.",
		capabilities: {
			terminal: true,
			desktop: true,
			cloud: true,
			extension: true,
			open_source: false,
		},
		features: [
			"Full codebase understanding",
			"Terminal command execution",
			"Git operations",
			"Multi-file editing",
		],
		pricing_model: "subscription",
		model_flexibility: "locked",
		context_approach: "project_memory",
		workflow_links: {
			desktop: "/agent-setup/claude-code/?view=desktop",
		},
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.anthropic.com/en/docs/claude-code",
			website: "https://claude.ai/code",
		},
	},
	{
		name: "Codex",
		vendor: "OpenAI",
		slug: "codex",
		icon: "codex",
		description:
			"OpenAI coding agent available through Codex CLI and Codex in the ChatGPT desktop app. It reads and writes files, runs commands, and browses the web in a sandbox.",
		capabilities: {
			terminal: true,
			desktop: true,
			cloud: true,
			extension: true,
			open_source: true,
		},
		features: [
			"File read/write operations",
			"Command execution",
			"Web browsing",
			"Sandboxed environment",
		],
		pricing_model: "hybrid",
		model_flexibility: "locked",
		context_approach: "project_memory",
		workflow_links: {
			desktop: "/agent-setup/codex/?view=desktop",
		},
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://developers.openai.com/codex/",
			website: "https://openai.com/codex",
		},
	},
	{
		name: "Cursor",
		vendor: "Cursor",
		slug: "cursor",
		icon: "cursor",
		description:
			"AI coding desktop app with multi-file edits, background agents, codebase search, and terminal access. Made by Cursor.",
		capabilities: {
			terminal: false,
			desktop: true,
			cloud: true,
			extension: false,
			open_source: false,
		},
		features: [
			"Multi-file Composer",
			"Background agents",
			"Codebase indexing",
			"Terminal integration",
		],
		pricing_model: "subscription",
		model_flexibility: "multi_provider",
		context_approach: "indexed_codebase",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.cursor.com",
			website: "https://cursor.sh",
		},
	},
	{
		name: "GitHub Copilot",
		vendor: "GitHub",
		slug: "github-copilot",
		icon: "copilot",
		description:
			"Coding agent available as a desktop app, IDE extension, and CLI with agent sessions and native GitHub integration. Made by GitHub.",
		capabilities: {
			terminal: true,
			desktop: true,
			cloud: true,
			extension: true,
			open_source: false,
		},
		features: [
			"Parallel agent sessions",
			"Workspace context",
			"CLI integration",
			"Pull request lifecycle",
		],
		pricing_model: "subscription",
		model_flexibility: "multi_provider",
		context_approach: "indexed_codebase",
		workflow_links: {
			terminal: "/agent-setup/github-copilot/?view=terminal",
			desktop: "/agent-setup/github-copilot/?view=desktop",
		},
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.github.com/en/copilot",
			website: "https://github.com/features/copilot",
		},
	},
	{
		name: "OpenCode",
		vendor: "Anomaly",
		slug: "opencode",
		icon: "opencode",
		description:
			"Open-source coding agent available as a terminal interface and desktop app. It works with 75+ LLMs. Made by Anomaly.",
		capabilities: {
			terminal: true,
			desktop: true,
			cloud: false,
			extension: false,
			open_source: true,
		},
		features: [
			"75+ model support",
			"Rich terminal TUI",
			"Built-in agents (build/plan)",
			"LSP integration",
		],
		pricing_model: "byok",
		model_flexibility: "multi_provider",
		context_approach: "project_memory",
		workflow_links: {
			desktop: "/agent-setup/opencode/?view=desktop",
		},
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://opencode.ai/docs",
			website: "https://opencode.ai",
		},
	},
	{
		name: "Windsurf",
		vendor: "Cognition",
		slug: "windsurf",
		icon: "windsurf",
		description:
			"AI coding desktop app with Cascade context and Flows for multi-step tasks. Made by Cognition.",
		capabilities: {
			terminal: false,
			desktop: true,
			cloud: false,
			extension: false,
			open_source: false,
		},
		features: [
			"Cascade context engine",
			"Flows automation",
			"Deep codebase search",
			"Command suggestions",
		],
		pricing_model: "subscription",
		model_flexibility: "multi_provider",
		context_approach: "indexed_codebase",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.windsurf.com",
			website: "https://windsurf.com",
		},
	},
	{
		name: "Visual Studio Code",
		vendor: "Microsoft",
		slug: "visual-studio-code",
		icon: "visual-studio-code",
		description:
			"Desktop code editor and agent control plane. Its Agents window can run and monitor Copilot, Claude, Codex, local, and cloud agent harnesses.",
		capabilities: {
			terminal: false,
			desktop: true,
			cloud: false,
			extension: false,
			open_source: true,
		},
		features: [
			"Multiple agent harnesses",
			"Agents window",
			"Terminal integration",
			"Native MCP client",
		],
		pricing_model: "byok",
		model_flexibility: "multi_provider",
		context_approach: "project_memory",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://code.visualstudio.com/docs",
			website: "https://code.visualstudio.com",
		},
	},
	{
		name: "Bionic",
		vendor: "LM Studio",
		slug: "bionic",
		icon: "bionic",
		description:
			"Powerful agent for coding and work. Natively local, with open models in the cloud. By LM Studio.",
		capabilities: {
			terminal: false,
			desktop: true,
			cloud: true,
			extension: false,
			open_source: false,
		},
		features: [
			"Local, remote, and cloud models",
			"Code Projects for local codebases",
			"Repository search and file editing",
			"Git and local shell tools",
		],
		pricing_model: "hybrid",
		model_flexibility: "multi_provider",
		links: {
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://lmstudio.ai/docs/bionic",
			website: "https://lmstudio.ai/",
		},
	},
];
