import type { AgentData } from "./types";

export const AGENTS: AgentData[] = [
	{
		name: "Claude Code",
		vendor: "Anthropic",
		slug: "claude-code",
		icon: "claude",
		description:
			"Terminal-based coding agent that understands your codebase, runs commands, edits files, and manages git. Made by Anthropic.",
		capabilities: {
			ide: false,
			terminal: true,
			standalone: true,
			cloud: true,
			extension: true,
			open_source: false,
		},
		features: [
			"Full codebase understanding",
			"Terminal command execution",
			"Git operations",
			"Multi-file editing",
		],
		pricing_model: "subscription",
		model_flexibility: "locked",
		context_approach: "project_memory",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.anthropic.com/en/docs/claude-code",
			website: "https://claude.ai/code",
		},
	},
	{
		name: "Codex",
		vendor: "OpenAI",
		slug: "codex",
		icon: "codex",
		description:
			"OpenAI coding agent available as a terminal CLI and desktop app. It reads and writes files, runs commands, and browses the web in a sandbox.",
		capabilities: {
			ide: false,
			terminal: true,
			standalone: true,
			cloud: true,
			extension: true,
			open_source: true,
		},
		features: [
			"File read/write operations",
			"Command execution",
			"Web browsing",
			"Sandboxed environment",
		],
		pricing_model: "hybrid",
		model_flexibility: "locked",
		context_approach: "project_memory",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://developers.openai.com/codex/",
			website: "https://openai.com/codex",
		},
	},
	{
		name: "Cursor",
		vendor: "Cursor",
		slug: "cursor",
		icon: "cursor",
		description:
			"AI-first IDE built on VS Code with multi-file Composer edits and background agents. Made by Cursor.",
		capabilities: {
			ide: true,
			terminal: true,
			standalone: true,
			cloud: true,
			extension: false,
			open_source: false,
		},
		features: [
			"Multi-file Composer",
			"Background agents",
			"Codebase indexing",
			"Terminal integration",
		],
		pricing_model: "subscription",
		model_flexibility: "multi_provider",
		context_approach: "indexed_codebase",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.cursor.com",
			website: "https://cursor.sh",
		},
	},
	{
		name: "GitHub Copilot",
		vendor: "GitHub",
		slug: "github-copilot",
		icon: "copilot",
		description:
			"Editor extension and CLI with agent mode, workspace context, and native PR integration. Made by GitHub.",
		capabilities: {
			ide: false,
			terminal: true,
			standalone: false,
			cloud: true,
			extension: true,
			open_source: false,
		},
		features: [
			"Agent mode",
			"Workspace context",
			"CLI integration",
			"PR summaries",
		],
		pricing_model: "subscription",
		model_flexibility: "multi_provider",
		context_approach: "indexed_codebase",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.github.com/en/copilot",
			website: "https://github.com/features/copilot",
		},
	},
	{
		name: "OpenCode",
		vendor: "Anomaly",
		slug: "opencode",
		icon: "opencode",
		description:
			"Open-source terminal agent with a rich TUI that works with 75+ LLMs. Made by Anomaly.",
		capabilities: {
			ide: false,
			terminal: true,
			standalone: true,
			cloud: false,
			extension: true,
			open_source: true,
		},
		features: [
			"75+ model support",
			"Rich terminal TUI",
			"Built-in agents (build/plan)",
			"LSP integration",
		],
		pricing_model: "byok",
		model_flexibility: "multi_provider",
		context_approach: "project_memory",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://opencode.ai/docs",
			website: "https://opencode.ai",
		},
	},
	{
		name: "Devin",
		vendor: "Cognition",
		slug: "devin",
		icon: "devin",
		description:
			"A full IDE with an agent manager built in — the command center for managing all your agents in one place. Made by Cognition.",
		capabilities: {
			terminal: true,
			ide: true,
			standalone: true,
			cloud: true,
			extension: true,
			open_source: false,
		},
		features: [
			"Agent Command Center",
			"Spaces for shared context",
			"Devin Local agent",
			"Multi-agent management",
		],
		pricing_model: "subscription",
		model_flexibility: "multi_provider",
		context_approach: "indexed_codebase",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://docs.devin.ai",
			website: "https://devin.ai",
		},
	},
	{
		name: "Visual Studio Code",
		vendor: "Microsoft",
		slug: "visual-studio-code",
		icon: "visual-studio-code",
		description:
			"Free, open-source code editor with native Model Context Protocol (MCP) client support and Copilot Chat integration. Made by Microsoft.",
		capabilities: {
			ide: true,
			terminal: true,
			standalone: true,
			cloud: false,
			extension: true,
			open_source: true,
		},
		features: [
			"Native MCP client",
			"Copilot Chat integration",
			"Terminal integration",
			"Extension ecosystem",
		],
		pricing_model: "byok",
		model_flexibility: "multi_provider",
		context_approach: "project_memory",
		links: {
			skills: "https://github.com/cloudflare/skills",
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://code.visualstudio.com/docs",
			website: "https://code.visualstudio.com",
		},
	},
	{
		name: "Bionic",
		vendor: "LM Studio",
		slug: "bionic",
		icon: "bionic",
		description:
			"Powerful agent for coding and work. Natively local, with open models in the cloud. By LM Studio.",
		capabilities: {
			ide: false,
			terminal: false,
			standalone: true,
			cloud: true,
			extension: false,
			open_source: false,
		},
		features: [
			"Local, remote, and cloud models",
			"Code Projects for local codebases",
			"Repository search and file editing",
			"Git and local shell tools",
		],
		pricing_model: "hybrid",
		model_flexibility: "multi_provider",
		links: {
			mcp_server: "https://github.com/cloudflare/mcp",
			mcp_server_domain: "https://github.com/cloudflare/mcp-server-cloudflare",
			docs: "https://lmstudio.ai/docs/bionic",
			website: "https://lmstudio.ai/",
		},
	},
];
