name: Request content addition
description: Request NEW documentation content.
labels: ["documentation", "content:new"]
body:
  - type: textarea
    id: location-urls
    validations:
      required: true
    attributes:
      label: Proposed changes
      description: Provide links to the top-level section of `https://developers.cloudflare.com/` or specific proposed pages.
      placeholder: |
        - https://developers.cloudflare.com/cloudflare-one/
        - https://developers.cloudflare.com/workers/examples/

  - type: input
    id: subject
    validations:
      required: true
    attributes:
      label: Subject Matter
      description: What needs to be documented?

  - type: textarea
    id: location
    validations:
      required: true
    attributes:
      label: Content Location
      placeholder: Should this be a new document, a new section within an existing document, or a call-out within a section?
      description: |
        Where would you expect this addition to be placed?
        Please provide any URLs to existing documents.

  - type: textarea
    id: extra
    validations:
      required: false
    attributes:
      label: Additional information
      description: Any other details or screenshots that may be relevant.
