name: Request content update
description: Request documentation content edits and/or clarifications.
labels: ["documentation", "content:edit"]
body:
  - type: textarea
    id: location-urls
    validations:
      required: true
    attributes:
      label: Existing documentation URL(s)
      description: Provide links to existing `https://developers.cloudflare.com/` pages.
      placeholder: |
        - https://developers.cloudflare.com/...
        - https://developers.cloudflare.com/...

  - type: textarea
    id: subject-what
    validations:
      required: true
    attributes:
      label: What changes are you suggesting?
      description: |
        - Give as much detail as you can to help us understand the change you want to see.
        - Why should the docs be changed? What use cases does it support?
        - What is the expected outcome?

  - type: textarea
    id: extra
    validations:
      required: false
    attributes:
      label: Additional information
      description: Any other details or screenshots that may be relevant.
