name: Website and/or content display error(s)
description: Report an issue with the live website; for example, issues with content display, buggy browser behavior, etc.
labels: ["engineering"]
assignees:
  - codewithkristian
body:
  - type: textarea
    id: location-urls
    validations:
      required: true
    attributes:
      label: Example URL(s)
      description: Please provide links that demonstrate the issue or behavior.
      placeholder: |
        - https://developers.cloudflare.com/...
        - https://developers.cloudflare.com/...

  - type: textarea
    id: actual
    validations:
      required: true
    attributes:
      label: Actual Behavior
      description: Explain the issue or undesired behavior.

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: Explain the expected behavior.

  - type: textarea
    id: extra
    validations:
      required: false
    attributes:
      label: Additional information
      description: Any other details or screenshots that may be relevant.
