name = "ssl"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true
kv-namespaces = [{ binding = "REDIRECTS_DEV", id = "59ccb75f5e064cd78291ad48c8c4bad0", preview_id = "59ccb75f5e064cd78291ad48c8c4bad0" }]

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/ssl*"
kv-namespaces = [{ binding = "REDIRECTS", id = "4ba7f2f2d6104584ba9e7417942518bc", preview_id = "4ba7f2f2d6104584ba9e7417942518bc" }]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
