name: Security

product:
  title: "Security (beta)"
  url: /security/
  show: false

meta:
  title: Cloudflare Security docs
  description: Documentation for Cloudflare app security products (with new user interface currently in beta).
  author: "@cloudflare"

externals:
  - title: Cloudflare homepage
    url: https://cloudflare.com
