content_dir: /src/content
authorized_users:
  - dcpena
  - kodster28
  - KianNH
  - marciocloudflare
  - pedrosousa
  - ranbel
  - RebeccaTamachiro
custom_style_guide:
  enabled: true
  check_status_upon_review_failure: success
reviewer:
  limit_num_reviews: 2
  limit_num_comments: 7
openapi:
  enabled: true
  urls:
    - https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json
