/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false` (hash: 290505c7c62e7f241df0eb645f5524bf)
interface __BaseEnv_Env {
	DOCS_FLUE_BUCKET: R2Bucket;
	AI: Ai;
	DOCS_FLUE_REVIEW_MODE: string;
	DOCS_FLUE_REVIEW_MODEL: string;
	DOCS_FLUE_VALIDATION_MODEL: string;
	DOCS_FLUE_ENABLE_EVAL_ROUTES: string;
	DOCS_FLUE_AI_GATEWAY_ID: string;
	DOCS_FLUE_GITHUB_APP_ID: string;
	DOCS_FLUE_GITHUB_APP_PRIVATE_KEY: string;
	DOCS_FLUE_GITHUB_INSTALLATION_ID: string;
	GITHUB_WEBHOOK_SECRET: string;
	GITHUB_ORG_TOKEN: string;
	DOCS_FLUE_INTERNAL_TOKEN: string;
	Sandbox: DurableObjectNamespace<import("./cloudflare").Sandbox>;
	REVIEW_COORDINATOR: DurableObjectNamespace<
		import("./cloudflare").ReviewCoordinator
	>;
	REVIEW_ORCHESTRATOR: Workflow<
		Parameters<import("./cloudflare").ReviewOrchestrator["run"]>[0]["payload"]
	>;
	REBASE: Workflow<
		Parameters<import("./cloudflare").RebaseWorkflow["run"]>[0]["payload"]
	>;
	INGEST: Workflow<
		Parameters<import("./cloudflare").IngestWorkflow["run"]>[0]["payload"]
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare");
		durableNamespaces:
			| "FlueConventionsReviewerAgent"
			| "FlueDependabotReviewerAgent"
			| "FlueRebaseConflictResolverAgent"
			| "FlueSpamFilterAgent"
			| "FlueReviewValidatorAgent"
			| "Sandbox"
			| "ReviewCoordinator"
			| "FlueReviewChunkAgent"
			| "FlueReconcileFindingsAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<
		Pick<
			Cloudflare.Env,
			| "DOCS_FLUE_REVIEW_MODE"
			| "DOCS_FLUE_REVIEW_MODEL"
			| "DOCS_FLUE_VALIDATION_MODEL"
			| "DOCS_FLUE_ENABLE_EVAL_ROUTES"
			| "DOCS_FLUE_AI_GATEWAY_ID"
			| "DOCS_FLUE_GITHUB_APP_ID"
			| "DOCS_FLUE_GITHUB_APP_PRIVATE_KEY"
			| "DOCS_FLUE_GITHUB_INSTALLATION_ID"
			| "GITHUB_WEBHOOK_SECRET"
			| "GITHUB_ORG_TOKEN"
			| "DOCS_FLUE_INTERNAL_TOKEN"
		>
	> {}
}
