export default {
  "/v4docs": "/fundamentals/api/how-to/make-api-calls/",
  "/tokens": "/fundamentals/api/get-started/",
  "/tokens/create": "/fundamentals/api/get-started/create-token/",
  "/tokens/create/template": "/fundamentals/api/reference/template/",
  "/tokens/create/permissions": "/fundamentals/api/reference/permissions/",
  "/tokens/advanced": "/fundamentals/api/how-to/",
  "/tokens/advanced/restrictions": "/fundamentals/api/how-to/restrict-tokens/",
  "/tokens/advanced/api": "/fundamentals/api/how-to/create-via-api/",
  "/keys": "/fundamentals/api/get-started/keys/",
  "/limits": "/fundamentals/api/reference/limits/",
  "/how-to/make-api-calls": "/fundamentals/api/how-to/make-api-calls/",
  "/get-started": "/fundamentals/api/get-started/",
  "/get-started/create-token": "/fundamentals/api/get-started/create-token/",
  "/reference/template": "/fundamentals/api/reference/template/",
  "/reference/permissions": "/fundamentals/api/reference/permissions/",
  "/how-to": "/fundamentals/api/how-to/",
  "/how-to/restrict-tokens": "/fundamentals/api/how-to/restrict-tokens/",
  "/how-to/create-via-api": "/fundamentals/api/how-to/create-via-api/",
  "/get-started/keys": "/fundamentals/api/get-started/keys/",
  "/reference/limits": "/fundamentals/api/reference/limits"
}