name = "byoip"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true
kv_namespaces = [{ binding = "REDIRECTS", id = "b393a548b93e4c36936e9276dedf5f5a", preview_id = "b393a548b93e4c36936e9276dedf5f5a" }]

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/byoip*"
kv_namespaces = [{ binding = "REDIRECTS", id = "327898e0657e4e609149720d0353b652", preview_id = "327898e0657e4e609149720d0353b652" }]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
