name = "image-resizing"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/image-resizing*"
kv_namespaces = [
    { binding = "REDIRECTS", id = "893c28b3008e425898a36aba02ae2f7d" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
