/* This is the allowlist for the tags we allow
in our page frontmatter. Refer to https://developers.cloudflare.com/style-guide/frontmatter/custom-properties/#tags
and https://developers.cloudflare.com/style-guide/frontmatter/tags/ for more details.
*/

type Tag = { label: string; variants?: string[] };

const data_structures: Array<Tag> = [
	{ label: "JSON" },
	{ label: "TOML" },
	{ label: "XML" },
	{ label: "YAML" },
];

const frameworks: Array<Tag> = [
	{ label: "Angular" },
	{ label: "Astro" },
	{ label: "Hono" },
	{ label: "Next.js", variants: ["nextjs"] },
	{ label: "Node.js", variants: ["node", "nodejs"] },
	{ label: "Nuxt" },
	{ label: "REST API" },
	{ label: "Remix" },
	{ label: "Ruby", variants: ["rb", "ruby on rails"] },
	{ label: "Svelte" },
	{ label: "SvelteKit" },
	{ label: "Vue.js", variants: ["vue", "vuejs"] },
	{ label: ".NET" },
];

const integrations: Array<Tag> = [
	{ label: "Azure", variants: ["Microsoft Azure", "MS Azure"] },
	{ label: "AWS", variants: ["Amazon Web Services"] },
	{ label: "Docker" },
	{ label: "GCP", variants: ["Google Cloud", "Google Cloud Platform"] },
	{ label: "Google" },
	{ label: "G Suite Group", variants: ["gsuite", "g suite"] },
	{ label: "CrowdStrike" },
	{ label: "GitHub" },
	{ label: "Gitlab" },
	{ label: "Grafana" },
	{ label: "Kubernetes", variants: ["K8s"] },
	{
		label: "Microsoft Entra ID",
		variants: ["AzureAD", "Azure Active Directory", "MS Entra ID", "Entra ID"],
	},
	{ label: "Microsoft" },
	{ label: "OpenAI" },
	{ label: "MongoDB" },
	{ label: "MotherDuck" },
	{ label: "PlanetScale" },
	{ label: "Postgres", variants: ["PostgreSQL"] },
	{ label: "S3" },
	{ label: "Salesforce" },
	{ label: "SentinelOne", variants: ["Sentinel One"] },
	{ label: "Sentry" },
	{ label: "Splunk" },
	{ label: "ServiceNow", variants: ["Service Now"] },
	{ label: "Slack" },
	{ label: "Stripe" },
	{ label: "Sumo Logic", variants: ["sumo"] },
	{ label: "Terraform" },
	{ label: "Okta" },
	{ label: "WordPress" },
];

const languages: Array<Tag> = [
	{ label: "Go" },
	{ label: "GraphQL" },
	{ label: "Java" },
	{ label: "JavaScript", variants: ["js"] },
	{ label: "Markdown", variants: ["md"] },
	{ label: "MySQL" },
	{ label: "NoSQL" },
	{ label: "PowerShell", variants: ["ps"] },
	{ label: "Python", variants: ["py"] },
	{ label: "Rust", variants: ["rs"] },
	{ label: "Shell", variants: ["sh"] },
	{ label: "SQL" },
	{ label: "TypeScript", variants: ["ts"] },
	{ label: "WebAssembly", variants: ["Web Assembly", "wasm"] },
];

const operating_systems: Array<Tag> = [
	{ label: "Android", variants: ["ChromeOS"] },
	{ label: "iOS" },
	{ label: "Linux" },
	{ label: "MacOS", variants: ["OS X"] },
	{ label: "Windows", variants: ["ms windows"] },
];

const presentation: Array<Tag> = [{ label: "Video" }];

const product_features: Array<Tag> = [
	{ label: "Web Crypto", variants: ["webcrypto"] },
	{ label: "RPC" },
];

const protocols: Array<Tag> = [
	{ label: "FTP", variants: ["file transfer protocol", "ftps"] },
	{ label: "ICMP" },
	{ label: "IPsec" },
	{ label: "IPv4" },
	{ label: "IPv6" },
	{ label: "JSON web token (JWT)", variants: ["jwt"] },
	{ label: "MASQUE" },
	{ label: "mTLS" },
	{ label: "NetFlow" },
	{ label: "MQTT" },
	{ label: "OIDC", variants: ["OpenID Connect", "oidc"] },
	{ label: "Post-quantum", variants: ["pqc", "post-quantum cryptography"] },
	{ label: "QUIC" },
	{ label: "RDP" },
	{ label: "SAML" },
	{ label: "SCIM" },
	{ label: "SMTP" },
	{ label: "SFTP" },
	{ label: "SSH" },
	{ label: "SSO" },
	{ label: "TCP" },
	{ label: "TLS" },
	{ label: "UDP" },
	{ label: "WebSockets", variants: ["websocket"] },
	{ label: "Wireguard" },
];

const use_cases: Array<Tag> = [
	{ label: "A11y", variants: ["accessibility"] },
	{ label: "Account takeover" },
	{ label: "AI" },
	{ label: "AI Agents", variants: ["agentic"] },
	{ label: "Analytics" },
	{ label: "Authentication", variants: ["auth"] },
	{ label: "Automation", variants: ["automations"] },
	{ label: "A/B testing", variants: ["ab test"] },
	{ label: "Bindings", variants: ["binding"] },
	{ label: "Caching", variants: ["cache"] },
	{ label: "CLI" },
	{ label: "CMS" },
	{ label: "Compliance" },
	{ label: "Cookies" },
	{ label: "CORS" },
	{ label: "CSP" },
	{ label: "Debugging", variants: ["debug", "troubleshooting"] },
	{ label: "DNS" },
	{ label: "Forms" },
	{ label: "Full stack", variants: ["full-stack"] },
	{ label: "Geolocation" },
	{ label: "Headers", variants: ["header"] },
	{ label: "Integration" },
	{ label: "LLM", variants: ["llms"] },
	{ label: "Localization" },
	{ label: "Logging" },
	{ label: "Middleware" },
	{ label: "Migration" },
	{ label: "MCP" },
	{ label: "Phishing" },
	{ label: "Playback" },
	{ label: "Posture", variants: ["security posture", "device posture"] },
	{ label: "Prisma ORM" },
	{ label: "Privacy" },
	{ label: "Proxying" },
	{ label: "Private networks" },
	{ label: "Redirects", variants: ["redirect"] },
	{ label: "Request modification", variants: ["request"] },
	{ label: "Response modification", variants: ["response"] },
	{ label: "Scraping" },
	{ label: "Security" },
	{ label: "SIEM" },
	{ label: "SPA" },
	{ label: "SSG" },
	{ label: "URL rewrite", variants: ["rewrite"] },
	{ label: "Voice" },
];

export const tags = {
	data_structures,
	frameworks,
	integrations,
	languages,
	presentation,
	product_features,
	protocols,
	operating_systems,
	use_cases,
};
