import { readdir } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import react from "@astrojs/react";
import icon from "astro-icon";
import nimbus, { defineConfig as defineNimbusConfig } from "nimbus-docs";
import { rehypePlugins } from "./plugins/rehype";

// One sidebar section per top-level product directory, autogenerated from the
// shared content tree (mirrors CF's `autogenSections` in the Starlight config).
// `scope: "section"` then surfaces only the current product's tree per page;
// without the full set, off-pilot pages fell back to the whole configured list.
async function autogenSections() {
	const dirs = await readdir("./src/content/docs/", { withFileTypes: true });
	return dirs
		.filter((entry) => entry.isDirectory() && entry.name !== "agent-setup")
		.map((entry) => ({
			label: entry.name,
			items: [{ autogenerate: { directory: entry.name, collapsed: true } }],
		}));
}

const sidebarItems = await autogenSections();

// Resolved against this file (src/nimbus/). `~` → src/nimbus, `~/assets` →
// the shared root src/assets, partials → the shared root src/content/partials.
const here = (p: string) =>
	fileURLToPath(new URL(p, import.meta.url)).replace(/\/$/, "");
const partialsRoot = here("../content/partials");

const nimbusConfig = defineNimbusConfig({
	site: "https://developers.cloudflare.com",
	title: "Cloudflare Docs",
	description: "Cloudflare's documentation.",
	locale: "en",
	github: "https://github.com/cloudflare/cloudflare-docs",
	socialImageAlt: "Cloudflare documentation",
	// Search is Algolia DocSearch (wired in E4); Pagefind off.
	search: false,
	sidebar: {
		items: sidebarItems,
		overviewLabel: "Overview",
		scope: "section",
		isolate: { boundaries: ["learning-paths/*"] },
		defaultCollapsed: true,
	},
});

// Maps Starlight icon names used in shared content to the iconify sets we ship,
// without touching content on disk: a pre-stage, MDX-scoped string rewrite.
const iconAlias = {
	name: "cf-nimbus:icon-alias",
	enforce: "pre" as const,
	transform(code: string, id: string) {
		const [pathOnly] = id.split("?", 1);
		if (!pathOnly?.endsWith(".mdx") && !pathOnly?.endsWith(".md")) return null;
		if (!/icon\s*=/.test(code)) return null;

		// Starlight ships a native `seti:` file-icon set; Nimbus routes icons
		// through astro-icon, which has no `seti` set. Map every `seti:` name the
		// shared content uses onto an installed set (vscode-icons / ph /
		// simple-icons). The substitute glyphs differ visually from Starlight's
		// seti set — a parity item tracked for the parity gate (Epic F), not a
		// render blocker.
		const SETI: Record<string, string> = {
			javascript: "vscode-icons:file-type-js-official",
			typescript: "vscode-icons:file-type-typescript-official",
			python: "vscode-icons:file-type-python",
			shell: "vscode-icons:file-type-shell",
			rust: "vscode-icons:file-type-rust",
			video: "vscode-icons:file-type-video",
			db: "vscode-icons:file-type-db",
			php: "vscode-icons:file-type-php",
			html: "vscode-icons:file-type-html",
			docker: "vscode-icons:file-type-docker",
			svelte: "vscode-icons:file-type-svelte",
			powershell: "vscode-icons:file-type-powershell",
			notebook: "vscode-icons:file-type-jupyter",
			nix: "vscode-icons:file-type-nix",
			json: "vscode-icons:file-type-json",
			java: "vscode-icons:file-type-java",
			go: "vscode-icons:file-type-go",
			"c-sharp": "vscode-icons:file-type-csharp",
			windows: "simple-icons:windows",
			linux: "simple-icons:linux",
			redhat: "simple-icons:redhat",
			debian: "simple-icons:debian",
			lock: "ph:lock",
			info: "ph:info",
			eye: "ph:eye",
			plan: "ph:file-text",
		};
		// Bare icon names (no set prefix) resolve against Starlight's built-in
		// icon set in the default build; under Nimbus they go through astro-icon
		// (local `src/icons` + installed iconify sets). Names not present locally
		// are mapped here onto an installed set. Glyphs differ visually from
		// Starlight's — a parity item for the parity gate (Epic F).
		const BARE: Record<string, string> = {
			document: "ph:file-text",
			"open-book": "ph:book-open",
			pen: "ph:pencil-simple",
			discord: "simple-icons:discord",
			"x.com": "simple-icons:x",
			apple: "ph:apple-logo",
			astro: "simple-icons:astro",
			bluesky: "simple-icons:bluesky",
			clock: "ph:clock",
			"comment-alt": "ph:chat-circle",
			connection: "ph:plugs-connected",
			database: "ph:database",
			download: "ph:download-simple",
			email: "ph:envelope-simple",
			error: "ph:warning-circle",
			external: "ph:arrow-square-out",
			github: "ph:github-logo",
			heart: "ph:heart",
			information: "ph:info",
			key: "ph:key",
			laptop: "ph:laptop",
			linux: "ph:linux-logo",
			"list-format": "ph:list-bullets",
			magnifier: "ph:magnifying-glass",
			mastodon: "ph:mastodon-logo",
			moon: "ph:moon",
			puzzle: "ph:puzzle-piece",
			rocket: "ph:rocket-launch",
			setting: "ph:gear",
			star: "ph:star",
			terminal: "ph:terminal",
		};

		let out = code;
		out = out.replace(/(["'])seti:([a-z0-9_-]+)\1/gi, (match, q, name) => {
			const mapped = SETI[name.toLowerCase()];
			return mapped ? `${q}${mapped}${q}` : match;
		});
		out = out.replace(
			/\bicon\s*=\s*(["'])([a-z0-9_.-]+)\1/gi,
			(match, q, name) => {
				if (name.includes(":")) return match;
				const mapped = BARE[name.toLowerCase()];
				return mapped ? `icon=${q}${mapped}${q}` : match;
			},
		);
		return out === code ? null : { code: out, map: null };
	},
};

// The Nimbus target's markdown / integrations / vite, branched into
// astro.config.ts when BUILD_TARGET=nimbus.
export const markdown = {
	syntaxHighlight: {
		type: "shiki" as const,
		excludeLangs: ["math", "mermaid"],
	},
	smartypants: false,
};

export const integrations = [
	icon(),
	react(),
	nimbus(nimbusConfig, {
		mdx: { optimize: true },
		markdown: { hastPlugins: rehypePlugins },
		incrementalBuilds: false,
		validateMdx: false,
		partialResolver: (name: string, props: Record<string, unknown>) => {
			if (name !== "Render" || !props.file) return null;
			const path = props.product
				? `${props.product}/${props.file}.mdx`
				: `${props.file}.mdx`;
			return resolve(partialsRoot, path);
		},
		rules: {
			"nimbus/frontmatter-shape": "error",
			"nimbus/image-ref": [
				"error",
				{ aliases: { "~/assets/": "src/assets/" } },
			],
			"nimbus/internal-link": "off",
		},
	}),
];

// Make the Nimbus app aliases authoritatively beat Astro's tsconfig-derived
// `~` (the root `~/*`→`src/*` the Starlight target needs).
//
// Astro injects the root tsconfig paths into `vite.resolve.alias` via the
// `astro:tsconfig-alias` plugin's `config()` hook, where the per-entry
// customResolver returns the ROOT file whenever `src/<path>` exists on disk.
// Vite's built-in `vite:alias` plugin (resolve.alias) runs BEFORE user
// `enforce:"pre"` plugins, so a `resolveId` override can never win where the
// root file exists (e.g. `~/components/changelog/Header.astro`).
//
// Fix: contribute our OWN `resolve.alias` entries from a `config` hook with
// `order: "post"`. Vite's `mergeAlias` PREPENDS each later config's aliases
// (`[...newer, ...older]`), and config hooks ordered "post" run after
// `astro:tsconfig-alias`'s (unordered) hook — so our entries land FIRST in
// the final alias array and the built-in alias plugin matches them first.
// `~/assets` and `~/content` precede `~` so the shared root tree still wins.
//
// This only applies to the Nimbus target (this config is loaded solely when
// BUILD_TARGET=nimbus); the default Starlight build is untouched and keeps
// `~`→src via its own tsconfig alias.
const nimbusDir = here(".");
const rootAssets = here("../assets");
const rootContent = here("../content");
const componentsBarrelId = normalizeId(here("./components.ts"));

function normalizeId(id: string) {
	return id.replace(/\\/g, "/").replace(/\?.*$/, "");
}

const componentsBarrelSideEffects = {
	name: "cf-nimbus:components-barrel-side-effects",
	enforce: "pre" as const,
	transform: {
		filter: { id: /[\\/]components\.ts(?:\?.*)?$/ },
		handler(code: string, id: string) {
			if (normalizeId(id) !== componentsBarrelId) return;
			return { code, moduleSideEffects: false };
		},
	},
};

const aliasResolver = {
	name: "cf-nimbus:alias",
	enforce: "pre" as const,
	config: {
		order: "post" as const,
		handler() {
			return {
				resolve: {
					alias: [
						// Shared content imports component barrels by name — both
						// Starlight's (`@astrojs/starlight/components`) and Expressive
						// Code's (`astro-expressive-code/components`, e.g. the workers
						// terraform changelog). Map both to the Nimbus barrel (which
						// re-exports those names, incl. `Code`) so byte-identical content
						// resolves without pulling in Starlight + Expressive Code (whose
						// `renderer.ts` needs `virtual:astro-expressive-code/config`, a
						// module only the EC integration — which Nimbus omits — provides).
						{
							find: /^@astrojs\/starlight\/components$/,
							replacement: `${nimbusDir}/components`,
						},
						{
							find: /^astro-expressive-code\/components$/,
							replacement: `${nimbusDir}/components`,
						},
						{ find: /^~\/assets(\/.*)?$/, replacement: `${rootAssets}$1` },
						{ find: /^~\/content(\/.*)?$/, replacement: `${rootContent}$1` },
						{ find: /^~(\/.*)?$/, replacement: `${nimbusDir}$1` },
						{ find: /^@(\/.*)?$/, replacement: `${nimbusDir}$1` },
					],
				},
			};
		},
	},
	// Defense-in-depth fallback for any context the alias array doesn't cover.
	async resolveId(
		this: { resolve: (s: string, i?: string, o?: object) => Promise<{ id: string } | null> },
		source: string,
		importer: string | undefined,
		options: object,
	) {
		let mapped: string | null = null;
		if (
			source === "@astrojs/starlight/components" ||
			source === "astro-expressive-code/components"
		)
			mapped = nimbusDir + "/components";
		else if (source === "~/assets" || source.startsWith("~/assets/"))
			mapped = rootAssets + source.slice("~/assets".length);
		else if (source === "~/content" || source.startsWith("~/content/"))
			mapped = rootContent + source.slice("~/content".length);
		else if (source === "~" || source.startsWith("~/"))
			mapped = nimbusDir + source.slice(1);
		else if (source === "@" || source.startsWith("@/"))
			mapped = nimbusDir + source.slice(1);
		if (mapped === null) return null;
		const resolved = await this.resolve(mapped, importer, { ...options, skipSelf: true });
		return resolved ?? { id: mapped };
	},
};

export const vite = {
	// Force a single React instance. `nimbus-docs` is consumed via a `link:`
	// symlink to the monorepo, which has its own React; without dedupe, Vite
	// can load two React copies across the symlink in dev and client islands
	// fail to hydrate with "jsxDEV is not a function".
	resolve: { dedupe: ["react", "react-dom"] },
	plugins: [aliasResolver, componentsBarrelSideEffects, iconAlias],
};
