// Generated by bin/generate-cf-config-reference.mjs from @cloudflare/config declarations.
export const CONFIG_REFERENCE = {
	package: "@cloudflare/config",
	version: "0.20.0",
	config: [
		{
			id: "Settings.accountId",
			name: "accountId",
			type: "string",
			required: false,
			description:
				"This is the ID of the account associated with your zone. It can also be specified through the `CLOUDFLARE_ACCOUNT_ID` environment variable.",
			internal: false,
			children: [],
		},
		{
			id: "Settings.complianceRegion",
			name: "complianceRegion",
			type: '"public" | "fedramp-high"',
			required: false,
			description:
				"The compliance boundary in which commands should operate. When omitted, this can be supplied through `CLOUDFLARE_COMPLIANCE_REGION`.",
			internal: false,
			children: [],
		},
		{
			id: "CloudflareConfig.worker",
			name: "worker",
			type: "ConfigInput<WorkerConfig>",
			required: false,
			description: "The Worker defined by this configuration.",
			internal: false,
			children: [],
		},
		{
			id: "CloudflareConfig.containers",
			name: "containers",
			type: "ConfigInput<ContainerConfig>[]",
			required: false,
			description: "Container applications defined by this configuration.",
			internal: false,
			children: [],
		},
	],
	worker: [
		{
			id: "WorkerConfig.name",
			name: "name",
			type: "string",
			required: true,
			description: "The name of your Worker.",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.compatibilityDate",
			name: "compatibilityDate",
			type: "string",
			required: true,
			description:
				"A date in the form yyyy-mm-dd, which will be used to determine which version of the Workers runtime is used. More details at https://developers.cloudflare.com/workers/configuration/compatibility-dates",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.compatibilityFlags",
			name: "compatibilityFlags",
			type: "string[]",
			required: false,
			description:
				"A list of flags that enable features from upcoming features of the Workers runtime, usually used together with `compatibilityDate`. More details at https://developers.cloudflare.com/workers/configuration/compatibility-flags/",
			default: "[]",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.entrypoint",
			name: "entrypoint",
			type: "string | WorkerModule",
			required: false,
			description:
				'The entrypoint module that will be executed. May be either a path string (e.g. `"./src/index.ts"`) or a module namespace imported with the `cf-worker` import attribute.',
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.assets",
			name: "assets",
			type: '{ /** How to handle HTML requests. */ htmlHandling?: "auto-trailing-slash" | "drop-trailing-slash" | "force-trailing-slash" | "none"; /** How to handle requests that do not match an asset. */ notFoundHandling?: "single-page-application" | "404-page" | "none"; /** * Matches will be routed to the User Worker, and matches to negative rules will go to the Asset Worker. * * Can also be `true`, indicating that every request should be routed to the User Worker. */ runWorkerFirst?: string[] | boolean; }',
			required: false,
			description:
				"Specify the directory of static assets to deploy/serve. More details at https://developers.cloudflare.com/workers/frameworks/ For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#assets",
			internal: false,
			children: [
				{
					name: "htmlHandling",
					type: '"auto-trailing-slash" | "drop-trailing-slash" | "force-trailing-slash" | "none"',
					required: false,
					description: "How to handle HTML requests.",
					children: [],
				},
				{
					name: "notFoundHandling",
					type: '"single-page-application" | "404-page" | "none"',
					required: false,
					description: "How to handle requests that do not match an asset.",
					children: [],
				},
				{
					name: "runWorkerFirst",
					type: "string[] | boolean",
					required: false,
					description:
						"Matches will be routed to the User Worker, and matches to negative rules will go to the Asset Worker. Can also be `true`, indicating that every request should be routed to the User Worker.",
					children: [],
				},
			],
		},
		{
			id: "WorkerConfig.domains",
			name: "domains",
			type: "string[]",
			required: false,
			description:
				"Custom domains that your Worker should be published to. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#types-of-routes",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.triggers",
			name: "triggers",
			type: "Trigger[]",
			required: false,
			description:
				"Event triggers — fetch routes, queue consumers, cron schedules, Email Routing addresses, and raw sockets — that invoke this Worker. Construct entries with `triggers.fetch(...)`, `triggers.queue(...)`, `triggers.scheduled(...)`, `triggers.email(...)`, or `triggers.connect(...)`. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#triggers",
			internal: false,
			children: [
				{
					name: "port",
					type: "number",
					required: true,
					description: "The port to listen on.",
					children: [],
				},
				{
					name: "address",
					type: "string",
					required: false,
					description: "The address to bind to. Defaults to `127.0.0.1`.",
					children: [],
				},
				{
					name: "protocol",
					type: '"tcp"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "protocol",
					type: '"udp"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "idleTimeoutMs",
					type: "number",
					required: false,
					description:
						"The idle timeout in milliseconds after which a peer flow is closed.",
					children: [],
				},
				{
					name: "maxPendingBytes",
					type: "number",
					required: false,
					description:
						"The maximum number of pending datagram bytes per peer flow.",
					children: [],
				},
				{
					name: "type",
					type: '"connect"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "type",
					type: '"email"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "type",
					type: '"fetch"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "type",
					type: '"queue"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "type",
					type: '"scheduled"',
					required: true,
					description: "",
					children: [],
				},
			],
		},
		{
			id: "WorkerConfig.tailConsumers",
			name: "tailConsumers",
			type: "Array<{ /** The name of the service tail events will be forwarded to. */ worker: string; /** Whether to stream tail events in real time. */ streaming?: boolean; }>",
			required: false,
			description:
				"A list of Tail Workers that are bound to this Worker. `@cloudflare/config` unifies regular and streaming tail consumers under a single field; pass `streaming: true` to forward streaming tail events.",
			default: "[]",
			internal: false,
			children: [
				{
					name: "worker",
					type: "string",
					required: true,
					description:
						"The name of the service tail events will be forwarded to.",
					children: [],
				},
				{
					name: "streaming",
					type: "boolean",
					required: false,
					description: "Whether to stream tail events in real time.",
					children: [],
				},
			],
		},
		{
			id: "WorkerConfig.cache",
			name: "cache",
			type: "{ /** If cache is enabled for this Worker. */ enabled: boolean; /** Whether cached assets may be reused across Worker versions. */ crossVersionCache?: boolean; }",
			required: false,
			description: "Specify the cache behavior of the Worker.",
			internal: false,
			children: [
				{
					name: "enabled",
					type: "boolean",
					required: true,
					description: "If cache is enabled for this Worker.",
					children: [],
				},
				{
					name: "crossVersionCache",
					type: "boolean",
					required: false,
					description:
						"Whether cached assets may be reused across Worker versions.",
					children: [],
				},
			],
		},
		{
			id: "WorkerConfig.placement",
			name: "placement",
			type: '{ mode: "off" | "smart"; hint?: string; } | { mode?: "targeted"; region: string; } | { mode?: "targeted"; host: string; } | { mode?: "targeted"; hostname: string; }',
			required: false,
			description:
				"Specify how the Worker should be located to minimize round-trip time. More details: https://developers.cloudflare.com/workers/platform/smart-placement/",
			internal: false,
			children: [
				{
					name: "mode",
					type: '"off" | "smart"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "hint",
					type: "string",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "mode",
					type: '"targeted"',
					required: false,
					description: "",
					children: [],
				},
				{
					name: "region",
					type: "string",
					required: true,
					description: "",
					children: [],
				},
				{
					name: "mode",
					type: '"targeted"',
					required: false,
					description: "",
					children: [],
				},
				{
					name: "host",
					type: "string",
					required: true,
					description: "",
					children: [],
				},
				{
					name: "mode",
					type: '"targeted"',
					required: false,
					description: "",
					children: [],
				},
				{
					name: "hostname",
					type: "string",
					required: true,
					description: "",
					children: [],
				},
			],
		},
		{
			id: "WorkerConfig.limits",
			name: "limits",
			type: "{ /** Maximum allowed CPU time for a Worker's invocation in milliseconds. */ cpuMs?: number; /** Maximum allowed number of fetch requests that a Worker's invocation can execute. */ subrequests?: number; }",
			required: false,
			description:
				'Specify limits for runtime behavior. Only supported for the "standard" Usage Model. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#limits',
			internal: false,
			children: [
				{
					name: "cpuMs",
					type: "number",
					required: false,
					description:
						"Maximum allowed CPU time for a Worker's invocation in milliseconds.",
					children: [],
				},
				{
					name: "subrequests",
					type: "number",
					required: false,
					description:
						"Maximum allowed number of fetch requests that a Worker's invocation can execute.",
					children: [],
				},
			],
		},
		{
			id: "WorkerConfig.logpush",
			name: "logpush",
			type: "boolean",
			required: false,
			description:
				"Send Trace Events from this Worker to Workers Logpush. This will not configure a corresponding Logpush job automatically. For more information about Workers Logpush, see: https://blog.cloudflare.com/logpush-for-workers/",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.observability",
			name: "observability",
			type: "{ /** If observability is enabled for this Worker. */ enabled?: boolean; /** The sampling rate. */ headSamplingRate?: number; /** * Whether query strings are removed from request URLs in logs and traces. * * @default false */ redactQueryString?: boolean; /** Real-time Issues settings for this Worker. */ issues?: { /** Whether real-time Issues are enabled. */ enabled?: boolean; }; logs?: { enabled?: boolean; /** The sampling rate. */ headSamplingRate?: number; /** Set to false to disable invocation logs. */ invocationLogs?: boolean; /** * If logs should be persisted to the Cloudflare observability platform where they can be queried in the dashboard. * * @default true */ persist?: boolean; /** * What destinations logs emitted from the Worker should be sent to. * * @default [] */ destinations?: string[]; }; traces?: { enabled?: boolean; /** The sampling rate. */ headSamplingRate?: number; /** * If traces should be persisted to the Cloudflare observability platform where they can be queried in the dashboard. * * @default true */ persist?: boolean; /** * What destinations traces emitted from the Worker should be sent to. * * @default [] */ destinations?: string[]; }; }",
			required: false,
			description:
				"Specify the observability behavior of the Worker. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#observability",
			internal: false,
			children: [
				{
					name: "enabled",
					type: "boolean",
					required: false,
					description: "If observability is enabled for this Worker.",
					children: [],
				},
				{
					name: "headSamplingRate",
					type: "number",
					required: false,
					description: "The sampling rate.",
					children: [],
				},
				{
					name: "redactQueryString",
					type: "boolean",
					required: false,
					description:
						"Whether query strings are removed from request URLs in logs and traces.",
					default: "false",
					children: [],
				},
				{
					name: "issues",
					type: "{ /** Whether real-time Issues are enabled. */ enabled?: boolean; }",
					required: false,
					description: "Real-time Issues settings for this Worker.",
					children: [
						{
							name: "enabled",
							type: "boolean",
							required: false,
							description: "Whether real-time Issues are enabled.",
							children: [],
						},
					],
				},
				{
					name: "logs",
					type: "{ enabled?: boolean; /** The sampling rate. */ headSamplingRate?: number; /** Set to false to disable invocation logs. */ invocationLogs?: boolean; /** * If logs should be persisted to the Cloudflare observability platform where they can be queried in the dashboard. * * @default true */ persist?: boolean; /** * What destinations logs emitted from the Worker should be sent to. * * @default [] */ destinations?: string[]; }",
					required: false,
					description: "",
					children: [
						{
							name: "enabled",
							type: "boolean",
							required: false,
							description: "",
							children: [],
						},
						{
							name: "headSamplingRate",
							type: "number",
							required: false,
							description: "The sampling rate.",
							children: [],
						},
						{
							name: "invocationLogs",
							type: "boolean",
							required: false,
							description: "Set to false to disable invocation logs.",
							children: [],
						},
						{
							name: "persist",
							type: "boolean",
							required: false,
							description:
								"If logs should be persisted to the Cloudflare observability platform where they can be queried in the dashboard.",
							default: "true",
							children: [],
						},
						{
							name: "destinations",
							type: "string[]",
							required: false,
							description:
								"What destinations logs emitted from the Worker should be sent to.",
							default: "[]",
							children: [],
						},
					],
				},
				{
					name: "traces",
					type: "{ enabled?: boolean; /** The sampling rate. */ headSamplingRate?: number; /** * If traces should be persisted to the Cloudflare observability platform where they can be queried in the dashboard. * * @default true */ persist?: boolean; /** * What destinations traces emitted from the Worker should be sent to. * * @default [] */ destinations?: string[]; }",
					required: false,
					description: "",
					children: [
						{
							name: "enabled",
							type: "boolean",
							required: false,
							description: "",
							children: [],
						},
						{
							name: "headSamplingRate",
							type: "number",
							required: false,
							description: "The sampling rate.",
							children: [],
						},
						{
							name: "persist",
							type: "boolean",
							required: false,
							description:
								"If traces should be persisted to the Cloudflare observability platform where they can be queried in the dashboard.",
							default: "true",
							children: [],
						},
						{
							name: "destinations",
							type: "string[]",
							required: false,
							description:
								"What destinations traces emitted from the Worker should be sent to.",
							default: "[]",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "WorkerConfig.workersDev",
			name: "workersDev",
			type: "boolean",
			required: false,
			description:
				"Whether we use `<name>.<subdomain>.workers.dev` to test and deploy your Worker. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#workersdev",
			default: "true",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.previewUrls",
			name: "previewUrls",
			type: "boolean",
			required: false,
			description:
				"Whether we use `<version>-<name>.<subdomain>.workers.dev` to serve Preview URLs for your Worker.",
			default: "false",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.unsafe",
			name: "unsafe",
			type: "{ /** * Arbitrary key/value pairs that will be included in the uploaded metadata. Values specified * here will always be applied to metadata last, so can add new or override existing fields. */ metadata?: Record<string, unknown>; /** * Used for internal capnp uploads for the Workers runtime. */ capnp?: { basePath: string; sourceSchemas: string[]; compiledSchema?: never; } | { basePath?: never; sourceSchemas?: never; compiledSchema: string; }; }",
			required: false,
			description:
				"\"Unsafe\" tables for runtime features that aren't directly supported by this configuration. Values are forwarded verbatim in the Worker's upload metadata.",
			default: "{}",
			internal: false,
			children: [
				{
					name: "metadata",
					type: "Record<string, unknown>",
					required: false,
					description:
						"Arbitrary key/value pairs that will be included in the uploaded metadata. Values specified here will always be applied to metadata last, so can add new or override existing fields.",
					children: [],
				},
				{
					name: "capnp",
					type: "{ basePath: string; sourceSchemas: string[]; compiledSchema?: never; } | { basePath?: never; sourceSchemas?: never; compiledSchema: string; }",
					required: false,
					description:
						"Used for internal capnp uploads for the Workers runtime.",
					children: [
						{
							name: "basePath",
							type: "string",
							required: true,
							description: "",
							children: [],
						},
						{
							name: "sourceSchemas",
							type: "string[]",
							required: true,
							description: "",
							children: [],
						},
						{
							name: "compiledSchema",
							type: "never",
							required: false,
							description: "",
							children: [],
						},
						{
							name: "basePath",
							type: "never",
							required: false,
							description: "",
							children: [],
						},
						{
							name: "sourceSchemas",
							type: "never",
							required: false,
							description: "",
							children: [],
						},
						{
							name: "compiledSchema",
							type: "string",
							required: true,
							description: "",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "WorkerConfig.env",
			name: "env",
			type: "Record<string, Binding>",
			required: false,
			description:
				"Bindings exposed on the Worker's `env` object. Construct entries with `bindings.kv(...)`, `bindings.r2(...)`, etc.",
			internal: false,
			children: [],
		},
		{
			id: "WorkerConfig.exports",
			name: "exports",
			type: "Record<string, Export>",
			required: false,
			description:
				"Configuration for named exports declared by the Worker. Each entry's key is the exported class name; the value configures the export. - Construct entries with `exports.durableObject(...)`. - Declares Durable Object classes exported from this Worker. For more information about Durable Objects, see the documentation at https://developers.cloudflare.com/workers/learning/using-durable-objects. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects. - Construct entries with `exports.workflow(...)`. - Declares Workflows defined by this Worker. For more information about Workflows, see the documentation at https://developers.cloudflare.com/workflows/.",
			internal: false,
			children: [],
		},
	],
	context: [
		{
			id: "ConfigContext.isPreview",
			name: "isPreview",
			type: "boolean",
			required: true,
			description: "Whether the config is being evaluated for a Preview build.",
			internal: false,
			children: [],
		},
		{
			id: "ConfigContext.mode",
			name: "mode",
			type: "string | undefined",
			required: true,
			description:
				"The mode the config is being evaluated in. Set via the `--mode` CLI flag. In Vite the mode defaults to `development` in `vite dev` and `production` in `vite build` ([more info](https://vite.dev/guide/env-and-mode.html#modes)). In Wrangler the mode defaults to `undefined`.",
			internal: false,
			children: [],
		},
	],
	bindings: [
		{
			id: "Bindings.agentMemory.default",
			name: "agentMemory",
			signature:
				"agentMemory(options: AgentMemoryBindingOptions): AgentMemoryBinding;",
			description:
				"Agent Memory namespace binding. Each binding is scoped to a namespace and allows agents to persist and recall memory.",
			parameterType: "AgentMemoryBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "namespace",
					type: "string",
					required: true,
					description:
						"The user-chosen namespace name. Must exist in Cloudflare at deploy time.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.ai.default",
			name: "ai",
			signature:
				"ai<TAiModelList extends AiModelListType = AiModels>(options?: AiBindingOptions): TypedAiBinding<TAiModelList>;",
			description:
				"Binding to the Workers AI project. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai",
			parameterType: "AiBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.aiSearch.default",
			name: "aiSearch",
			signature: "aiSearch(options: AiSearchBindingOptions): AiSearchBinding;",
			description:
				'AI Search instance binding. Each binding is bound directly to a single pre-existing instance within the "default" namespace.',
			parameterType: "AiSearchBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "name",
					type: "string",
					required: true,
					description:
						"The user-chosen instance name. Must exist in Cloudflare at deploy time.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.aiSearchNamespace.default",
			name: "aiSearchNamespace",
			signature:
				"aiSearchNamespace(options: AiSearchNamespaceBindingOptions): AiSearchNamespaceBinding;",
			description:
				"AI Search namespace binding. Each binding is scoped to a namespace and allows dynamic instance CRUD within it.",
			parameterType: "AiSearchNamespaceBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "namespace",
					type: "string",
					required: true,
					description:
						"The user-chosen namespace name. Must exist in Cloudflare at deploy time.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.analyticsEngineDataset.default",
			name: "analyticsEngineDataset",
			signature:
				"analyticsEngineDataset(options?: AnalyticsEngineDatasetBindingOptions): AnalyticsEngineDatasetBinding;",
			description:
				"Binding to an Analytics Engine dataset. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#analytics-engine-datasets",
			parameterType: "AnalyticsEngineDatasetBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "name",
					type: "string",
					required: false,
					description: "The name of this dataset to write to.",
					children: [],
				},
			],
		},
		{
			id: "Bindings.artifacts.default",
			name: "artifacts",
			signature:
				"artifacts(options: ArtifactsBindingOptions): ArtifactsBinding;",
			description:
				"Binding to an Artifacts instance. Artifacts provides git-compatible file storage on Cloudflare Workers.",
			parameterType: "ArtifactsBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "namespace",
					type: "string",
					required: true,
					description: "The namespace to use.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.assets.default",
			name: "assets",
			signature: "assets(): AssetsBinding;",
			description:
				"Binding to the Worker's static assets. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#assets",
			parameterType: "unknown",
			parameterOptional: false,
			children: [],
		},
		{
			id: "Bindings.browser.default",
			name: "browser",
			signature: "browser(options?: BrowserBindingOptions): BrowserBinding;",
			description:
				"Binding to a headless browser usable from the Worker. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#browser-rendering",
			parameterType: "BrowserBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.d1.default",
			name: "d1",
			signature: "d1(options?: D1BindingOptions): D1Binding;",
			description:
				"Binding to a D1 database. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases",
			parameterType: "D1BindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "id",
					type: "string",
					required: false,
					description: "The UUID of this D1 database (not required).",
					children: [],
				},
				{
					name: "name",
					type: "string",
					required: false,
					description: "The name of this D1 database.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.dispatchNamespace.default",
			name: "dispatchNamespace",
			signature:
				"dispatchNamespace(options?: DispatchNamespaceBindingOptions): DispatchNamespaceBinding;",
			description:
				"Binding to a Workers for Platforms dispatch namespace. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#dispatch-namespace-bindings-workers-for-platforms",
			parameterType: "DispatchNamespaceBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "namespace",
					type: "string",
					required: false,
					description: "The namespace to bind to.",
					children: [],
				},
				{
					name: "outbound",
					type: "{ /** Name of the Worker handling the outbound requests. */ worker: string; /** (Optional) List of parameter names, for sending context from your dispatch Worker to the outbound handler. */ parameters?: string[]; }",
					required: false,
					description:
						"Details about the outbound Worker which will handle outbound requests from your namespace.",
					children: [
						{
							name: "worker",
							type: "string",
							required: true,
							description: "Name of the Worker handling the outbound requests.",
							children: [],
						},
						{
							name: "parameters",
							type: "string[]",
							required: false,
							description:
								"(Optional) List of parameter names, for sending context from your dispatch Worker to the outbound handler.",
							children: [],
						},
					],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.durableObject.all",
			name: "durableObject",
			signature:
				"durableObject<TWorker$1 extends WorkerReference, TExportName$1 extends DurableObjectExportName<TWorker$1>>(options: DurableObjectBindingOptions<TWorker$1, TExportName$1>): DurableObjectBinding<TWorker$1, TExportName$1>;",
			description:
				"Binding to a Durable Object class. `worker` is the name or config of the Worker that defines the class; `exportName` is the exported class name. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects",
			parameterType: "DurableObjectBindingOptions<TWorker$1, TExportName$1>",
			parameterOptional: false,
			children: [
				{
					name: "worker",
					type: "TWorker$1",
					required: true,
					description:
						"The name or config of the Worker that defines the Durable Object class.",
					children: [],
				},
				{
					name: "exportName",
					type: "TExportName$1",
					required: true,
					description: "The exported class name of the Durable Object.",
					children: [],
				},
			],
		},
		{
			id: "Bindings.flagship.default",
			name: "flagship",
			signature: "flagship(options?: FlagshipBindingOptions): FlagshipBinding;",
			description: "Binding to a Flagship feature-flag service.",
			parameterType: "FlagshipBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "id",
					type: "string",
					required: false,
					description: "The Flagship app ID to bind to.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.hyperdrive.default",
			name: "hyperdrive",
			signature:
				"hyperdrive(options: HyperdriveBindingOptions): HyperdriveBinding;",
			description:
				"Binding to a Hyperdrive configuration. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#hyperdrive",
			parameterType: "HyperdriveBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "id",
					type: "string",
					required: true,
					description: "The ID of the Hyperdrive configuration.",
					children: [],
				},
				{
					name: "dev",
					type: "{ /** The database connection string used during local development. */ connectionString?: string; }",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "connectionString",
							type: "string",
							required: false,
							description:
								"The database connection string used during local development.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.images.default",
			name: "images",
			signature: "images(options?: ImagesBindingOptions): ImagesBinding$1;",
			description:
				"Binding to Cloudflare Images. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#images",
			parameterType: "ImagesBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.json.default",
			name: "json",
			signature: "json<T$1 extends Json>(value: T$1): JsonBinding<T$1>;",
			description:
				"Inline JSON value made available to the Worker on `env` under the binding name.",
			parameterType: "T$1",
			parameterOptional: false,
			children: [],
		},
		{
			id: "Bindings.kv.default",
			name: "kv",
			signature:
				"kv<TKey extends string = string>(options?: KvBindingOptions): TypedKvBinding<TKey>;",
			description:
				"Binding to a Workers KV namespace. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces",
			parameterType: "KvBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "id",
					type: "string",
					required: false,
					description: "The ID of the KV namespace.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.logfwdr.default",
			name: "logfwdr",
			signature: "logfwdr(options: LogfwdrBindingOptions): LogfwdrBinding;",
			description: "Binding for forwarding logs to logfwdr.",
			parameterType: "LogfwdrBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "destination",
					type: "string",
					required: true,
					description: "The destination for this logged message.",
					children: [],
				},
			],
		},
		{
			id: "Bindings.media.default",
			name: "media",
			signature: "media(options?: MediaBindingOptions): MediaBinding$1;",
			description: "Binding to Cloudflare Media Transformations.",
			parameterType: "MediaBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.mtlsCertificate.default",
			name: "mtlsCertificate",
			signature:
				"mtlsCertificate(options: MtlsCertificateBindingOptions): MtlsCertificateBinding;",
			description:
				"Binding to an uploaded mTLS certificate. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#mtls-certificates",
			parameterType: "MtlsCertificateBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "id",
					type: "string",
					required: true,
					description: "The UUID of the uploaded mTLS certificate.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.pipeline.default",
			name: "pipeline",
			signature:
				"pipeline<TRecord extends PipelineRecord = PipelineRecord>(options: PipelineBindingOptions): TypedPipelineBinding<TRecord>;",
			description: "Binding to a Cloudflare Pipeline.",
			parameterType: "PipelineBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "name",
					type: "string",
					required: true,
					description: "Name of the Pipeline to bind.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.queue.default",
			name: "queue",
			signature:
				"queue<TBody = unknown>(options?: QueueBindingOptions): TypedQueueBinding<TBody>;",
			description:
				"Producer binding to a Cloudflare Queue. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#queues",
			parameterType: "QueueBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "name",
					type: "string",
					required: false,
					description: "The name of this Queue.",
					children: [],
				},
				{
					name: "deliveryDelay",
					type: "number",
					required: false,
					description:
						"The number of seconds to wait before delivering a message.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.r2.default",
			name: "r2",
			signature: "r2(options?: R2BindingOptions): R2Binding;",
			description:
				"Binding to an R2 bucket. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets",
			parameterType: "R2BindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "name",
					type: "string",
					required: false,
					description: "The name of this R2 bucket at the edge.",
					children: [],
				},
				{
					name: "jurisdiction",
					type: "string",
					required: false,
					description:
						"The jurisdiction that the bucket exists in. Default if not present.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions & { /** EXPERIMENTAL: credentials for the local S3-compatible endpoint. */ experimentalS3Credentials?: { accessKeyId: string; secretAccessKey: string; }; }",
					required: false,
					description: "Settings that only apply to local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
						{
							name: "experimentalS3Credentials",
							type: "{ accessKeyId: string; secretAccessKey: string; }",
							required: false,
							description:
								"EXPERIMENTAL: credentials for the local S3-compatible endpoint.",
							children: [
								{
									name: "accessKeyId",
									type: "string",
									required: true,
									description: "",
									children: [],
								},
								{
									name: "secretAccessKey",
									type: "string",
									required: true,
									description: "",
									children: [],
								},
							],
						},
					],
				},
			],
		},
		{
			id: "Bindings.rateLimit.default",
			name: "rateLimit",
			signature:
				"rateLimit(options: RateLimitBindingOptions): RateLimitBinding;",
			description: "Binding to a rate limiter.",
			parameterType: "RateLimitBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "namespace",
					type: "string",
					required: true,
					description: "The namespace ID for this rate limiter.",
					children: [],
				},
				{
					name: "simple",
					type: "{ /** The maximum number of requests allowed in the time period. */ limit: number; /** The time period in seconds (10 for ten seconds, 60 for one minute). */ period: 10 | 60; }",
					required: true,
					description: "Simple rate limiting configuration.",
					children: [
						{
							name: "limit",
							type: "number",
							required: true,
							description:
								"The maximum number of requests allowed in the time period.",
							children: [],
						},
						{
							name: "period",
							type: "10 | 60",
							required: true,
							description:
								"The time period in seconds (10 for ten seconds, 60 for one minute).",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.secret.default",
			name: "secret",
			signature: "secret(): SecretBinding;",
			description:
				"Declares a secret that is required by your Worker, exposed on `env` under the binding name. When defined, this binding: - Replaces .dev.vars/.env/process.env inference for type generation - Enables local dev validation with warnings for missing secrets For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#secrets-configuration-property",
			parameterType: "unknown",
			parameterOptional: false,
			children: [],
		},
		{
			id: "Bindings.secretsStoreSecret.default",
			name: "secretsStoreSecret",
			signature:
				"secretsStoreSecret(options: SecretsStoreSecretBindingOptions): SecretsStoreSecretBinding;",
			description: "Binding to a Secrets Store secret.",
			parameterType: "SecretsStoreSecretBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "storeId",
					type: "string",
					required: true,
					description: "ID of the secret store.",
					children: [],
				},
				{
					name: "secretName",
					type: "string",
					required: true,
					description: "Name of the secret.",
					children: [],
				},
			],
		},
		{
			id: "Bindings.sendEmail.default",
			name: "sendEmail",
			signature:
				"sendEmail(options?: SendEmailBindingOptions): SendEmailBinding;",
			description:
				"Binding for sending email from inside the Worker. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#email-bindings",
			parameterType: "SendEmailBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "destinationAddress",
					type: "string",
					required: true,
					description:
						"If this binding should be restricted to a specific verified address.",
					children: [],
				},
				{
					name: "allowedDestinationAddresses",
					type: "never",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "destinationAddress",
					type: "never",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "allowedDestinationAddresses",
					type: "string[]",
					required: true,
					description:
						"If this binding should be restricted to a set of verified addresses.",
					children: [],
				},
				{
					name: "destinationAddress",
					type: "never",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "allowedDestinationAddresses",
					type: "never",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "allowedSenderAddresses",
					type: "string[]",
					required: false,
					description:
						"If this binding should be restricted to a set of sender addresses.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.stream.default",
			name: "stream",
			signature: "stream(options?: StreamBindingOptions): StreamBinding$1;",
			description: "Binding to Cloudflare Stream.",
			parameterType: "StreamBindingOptions",
			parameterOptional: true,
			children: [
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.text.default",
			name: "text",
			signature: "text<T$1 extends string>(value: T$1): TextBinding<T$1>;",
			description:
				"Inline string value made available to the Worker on `env` under the binding name. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables",
			parameterType: "T$1",
			parameterOptional: false,
			children: [],
		},
		{
			id: "Bindings.vectorize.default",
			name: "vectorize",
			signature:
				"vectorize(options: VectorizeBindingOptions): VectorizeBinding;",
			description:
				"Binding to a Vectorize index. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#vectorize-indexes",
			parameterType: "VectorizeBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "name",
					type: "string",
					required: true,
					description: "The name of the Vectorize index.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.versionMetadata.default",
			name: "versionMetadata",
			signature: "versionMetadata(): VersionMetadataBinding;",
			description: "Binding to the Worker version's metadata.",
			parameterType: "unknown",
			parameterOptional: false,
			children: [],
		},
		{
			id: "Bindings.vpcNetwork.default",
			name: "vpcNetwork",
			signature:
				"vpcNetwork(options: VpcNetworkBindingOptions): VpcNetworkBinding;",
			description: "Binding to a VPC network.",
			parameterType: "VpcNetworkBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "tunnelId",
					type: "string",
					required: true,
					description:
						"The tunnel ID of the Cloudflare Tunnel to route traffic through. Mutually exclusive with `networkId`.",
					children: [],
				},
				{
					name: "networkId",
					type: "never",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
				{
					name: "tunnelId",
					type: "never",
					required: false,
					description: "",
					children: [],
				},
				{
					name: "networkId",
					type: "string",
					required: true,
					description:
						"The network ID to route traffic through. Mutually exclusive with `tunnelId`.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.vpcService.default",
			name: "vpcService",
			signature:
				"vpcService(options: VpcServiceBindingOptions): VpcServiceBinding;",
			description: "Binding to a VPC service.",
			parameterType: "VpcServiceBindingOptions",
			parameterOptional: false,
			children: [
				{
					name: "id",
					type: "string",
					required: true,
					description: "The service ID of the VPC connectivity service.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.worker.default",
			name: "worker",
			signature:
				"worker<TWorker$1 extends WorkerReference, TExportName$1 extends WorkerEntrypointExportName<TWorker$1> | undefined = undefined>(options: WorkerBindingOptions<TWorker$1, TExportName$1>): WorkerBinding<TWorker$1, NoInfer<TExportName$1>>;",
			description:
				"Service binding (Worker-to-Worker). `worker` is the name or config of the bound Worker; `exportName` selects a named `WorkerEntrypoint` export (defaults to the default export). For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings",
			parameterType: "WorkerBindingOptions<TWorker$1, TExportName$1>",
			parameterOptional: false,
			children: [
				{
					name: "worker",
					type: "TWorker$1",
					required: true,
					description: "The name or config of the bound Worker.",
					children: [],
				},
				{
					name: "exportName",
					type: "TExportName$1",
					required: false,
					description:
						"The named export to bind to (defaults to the default export).",
					children: [],
				},
				{
					name: "props",
					type: "Record<string, unknown>",
					required: false,
					description:
						"Optional properties that will be made available to the service via `ctx.props`.",
					children: [],
				},
				{
					name: "dev",
					type: "BindingDevOptions",
					required: false,
					description: "Options that only apply during local development.",
					children: [
						{
							name: "remote",
							type: "boolean",
							required: false,
							description:
								"Whether the binding should connect to the remote resource.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Bindings.workerLoader.default",
			name: "workerLoader",
			signature: "workerLoader(): WorkerLoaderBinding;",
			description: "Binding to a Worker Loader.",
			parameterType: "unknown",
			parameterOptional: false,
			children: [],
		},
		{
			id: "Bindings.workflow.default",
			name: "workflow",
			signature:
				"workflow<TWorker$1 extends WorkerReference, TExportName$1 extends WorkflowExportName<TWorker$1>>(options: WorkflowBindingOptions<TWorker$1, TExportName$1>): WorkflowBinding<TWorker$1, NoInfer<TExportName$1>>;",
			description:
				"Create a Workflow binding. `worker` may be a Worker config reference or a Worker name. `exportName` must be a valid `WorkflowEntrypoint` export for the given Worker.",
			parameterType: "WorkflowBindingOptions<TWorker$1, TExportName$1>",
			parameterOptional: false,
			children: [
				{
					name: "name",
					type: "string",
					required: true,
					description: "The name of the Workflow.",
					children: [],
				},
				{
					name: "worker",
					type: "TWorker$1",
					required: true,
					description:
						"The name or config of the Worker that defines the Workflow.",
					children: [],
				},
				{
					name: "exportName",
					type: "TExportName$1",
					required: true,
					description: "The exported class name of the Workflow.",
					children: [],
				},
			],
		},
	],
	triggers: [
		{
			id: "Triggers.fetch.default",
			name: "fetch",
			signature: "fetch(options: FetchTriggerOptions): FetchTrigger;",
			description:
				"Fetch trigger — a route that your Worker should be published to. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#types-of-routes",
			parameterType: "FetchTriggerOptions",
			parameterOptional: false,
			children: [
				{
					name: "pattern",
					type: "string",
					required: true,
					description:
						"A route that your Worker should be published to. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#types-of-routes",
					children: [],
				},
				{
					name: "zone",
					type: "string",
					required: false,
					description:
						"The DNS zone the pattern is attached to. Required when the pattern is ambiguous.",
					children: [],
				},
			],
		},
		{
			id: "Triggers.queue.default",
			name: "queue",
			signature:
				"queue(options: QueueConsumerTriggerOptions): QueueConsumerTrigger;",
			description:
				"Queue consumer trigger — invokes this Worker when messages arrive on the named queue. For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#queues",
			parameterType: "QueueConsumerTriggerOptions",
			parameterOptional: false,
			children: [
				{
					name: "name",
					type: "string",
					required: true,
					description:
						"The name of the queue from which this consumer should consume.",
					children: [],
				},
				{
					name: "deadLetterQueue",
					type: "string",
					required: false,
					description: "The queue to send messages that failed to be consumed.",
					children: [],
				},
				{
					name: "maxBatchSize",
					type: "number",
					required: false,
					description: "The maximum number of messages per batch.",
					children: [],
				},
				{
					name: "maxBatchTimeout",
					type: "number",
					required: false,
					description:
						"The maximum number of seconds to wait to fill a batch with messages.",
					children: [],
				},
				{
					name: "maxConcurrency",
					type: "number | null",
					required: false,
					description:
						"The maximum number of concurrent consumer Worker invocations. Leaving this unset will allow your consumer to scale to the maximum concurrency needed to keep up with the message backlog.",
					children: [],
				},
				{
					name: "maxRetries",
					type: "number",
					required: false,
					description: "The maximum number of retries for each message.",
					children: [],
				},
				{
					name: "retryDelay",
					type: "number",
					required: false,
					description:
						"The number of seconds to wait before retrying a message.",
					children: [],
				},
				{
					name: "visibilityTimeoutMs",
					type: "number",
					required: false,
					description:
						"The number of milliseconds to wait for pulled messages to become visible again.",
					children: [],
				},
			],
		},
		{
			id: "Triggers.scheduled.default",
			name: "scheduled",
			signature:
				"scheduled(options: ScheduledTriggerOptions): ScheduledTrigger;",
			description:
				"Scheduled (cron) trigger — invokes this Worker on the given schedules. More details here https://developers.cloudflare.com/workers/platform/cron-triggers",
			parameterType: "ScheduledTriggerOptions",
			parameterOptional: false,
			children: [
				{
					name: "schedule",
					type: "string",
					required: true,
					description:
						'A "cron" definition to trigger a Worker\'s "scheduled" function. Lets you call Workers periodically, much like a cron job. More details here https://developers.cloudflare.com/workers/platform/cron-triggers',
					children: [],
				},
			],
		},
		{
			id: "Triggers.email.default",
			name: "email",
			signature: "email(options: EmailTriggerOptions): EmailTrigger;",
			description:
				"Email trigger — invokes this Worker for the configured Email Routing addresses.",
			parameterType: "EmailTriggerOptions",
			parameterOptional: false,
			children: [
				{
					name: "addresses",
					type: "string[]",
					required: true,
					description:
						'Inbound Email Routing addresses handled by this Worker. Each entry is a literal recipient address (e.g. `"support@example.com"`) or a `*@domain` catch-all (e.g. `"*@example.com"`).',
					children: [],
				},
			],
		},
		{
			id: "Triggers.connect.default",
			name: "connect",
			signature: "connect(options: ConnectTriggerOptions): ConnectTrigger;",
			description:
				"Connect trigger — invokes this Worker's `connect(socket, env, ctx)` handler for raw socket connections received on the configured protocol/port.",
			parameterType: "ConnectTriggerOptions",
			parameterOptional: false,
			children: [
				{
					name: "port",
					type: "number",
					required: true,
					description: "The port to listen on.",
					children: [],
				},
				{
					name: "address",
					type: "string",
					required: false,
					description: "The address to bind to. Defaults to `127.0.0.1`.",
					children: [],
				},
				{
					name: "protocol",
					type: '"tcp"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "protocol",
					type: '"udp"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "idleTimeoutMs",
					type: "number",
					required: false,
					description:
						"The idle timeout in milliseconds after which a peer flow is closed.",
					children: [],
				},
				{
					name: "maxPendingBytes",
					type: "number",
					required: false,
					description:
						"The maximum number of pending datagram bytes per peer flow.",
					children: [],
				},
			],
		},
	],
	exports: [
		{
			id: "Exports.durableObject.created",
			name: "durableObject",
			signature:
				"durableObject<TContainer extends ContainerDefinition | undefined = undefined>(options: DurableObjectCreatedExportOptions<TContainer>): DurableObjectCreatedExport<TContainer>;",
			description:
				"Declares a Durable Object class defined by this Worker. For more information about Durable Objects, see the documentation at https://developers.cloudflare.com/workers/learning/using-durable-objects For reference, see https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects",
			parameterType: "DurableObjectCreatedExportOptions<TContainer>",
			parameterOptional: false,
			children: [
				{
					name: "state",
					type: '"created"',
					required: false,
					description: "",
					children: [],
				},
				{
					name: "storage",
					type: '"sqlite"',
					required: true,
					description:
						"Selects the SQLite-backed storage engine (recommended for new classes).",
					children: [],
				},
				{
					name: "container",
					type: "TContainer",
					required: false,
					description:
						"Attach a Container application to this Durable Object by config reference.",
					children: [],
				},
				{
					name: "storage",
					type: '"legacy-kv"',
					required: true,
					description: "Selects the legacy key-value storage engine.",
					children: [],
				},
			],
		},
		{
			id: "Exports.durableObject.deleted",
			name: "durableObject",
			signature:
				"durableObject(options: DurableObjectDeletedExportOptions): DurableObjectDeletedExport;",
			description:
				"Retire a provisioned Durable Object namespace whose class has been removed from code.",
			parameterType: "DurableObjectDeletedExportOptions",
			parameterOptional: false,
			children: [
				{
					name: "state",
					type: '"deleted"',
					required: true,
					description: "",
					children: [],
				},
			],
		},
		{
			id: "Exports.durableObject.renamed",
			name: "durableObject",
			signature:
				"durableObject(options: DurableObjectRenamedExportOptions): DurableObjectRenamedExport;",
			description: "Rename a provisioned Durable Object namespace's class.",
			parameterType: "DurableObjectRenamedExportOptions",
			parameterOptional: false,
			children: [
				{
					name: "state",
					type: '"renamed"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "renamedTo",
					type: "string",
					required: true,
					description:
						'The destination class name. Must be a valid JavaScript identifier and must appear as a live (`state: "created"`) `durableObject` entry in the same `exports` map.',
					children: [],
				},
			],
		},
		{
			id: "Exports.durableObject.transferred",
			name: "durableObject",
			signature:
				"durableObject(options: DurableObjectTransferredExportOptions): DurableObjectTransferredExport;",
			description:
				"Transfer ownership of a Durable Object namespace to another Worker in the same account.",
			parameterType: "DurableObjectTransferredExportOptions",
			parameterOptional: false,
			children: [
				{
					name: "state",
					type: '"transferred"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "transferredTo",
					type: "string",
					required: true,
					description:
						"The destination Worker. Must reference a Worker in the same account.",
					children: [],
				},
			],
		},
		{
			id: "Exports.durableObject.expecting-transfer",
			name: "durableObject",
			signature:
				"durableObject<TContainer extends ContainerDefinition | undefined = undefined>(options: DurableObjectExpectingTransferExportOptions<TContainer>): DurableObjectExpectingTransferExport<TContainer>;",
			description:
				"Prepare to receive cross-Worker Durable Object transfer. The source Worker must follow up with a deployment containing a `transferred` export to commit the transfer.",
			parameterType: "DurableObjectExpectingTransferExportOptions<TContainer>",
			parameterOptional: false,
			children: [
				{
					name: "state",
					type: '"expecting-transfer"',
					required: true,
					description: "",
					children: [],
				},
				{
					name: "transferFrom",
					type: "string",
					required: true,
					description:
						"The source Worker for the two-phase cross-Worker transfer.",
					children: [],
				},
				{
					name: "storage",
					type: '"sqlite"',
					required: true,
					description:
						"Selects the SQLite-backed storage engine (recommended for new classes).",
					children: [],
				},
				{
					name: "container",
					type: "TContainer",
					required: false,
					description:
						"Attach a Container application to this Durable Object by config reference.",
					children: [],
				},
				{
					name: "storage",
					type: '"legacy-kv"',
					required: true,
					description: "Selects the legacy key-value storage engine.",
					children: [],
				},
			],
		},
		{
			id: "Exports.worker.default",
			name: "worker",
			signature:
				"worker(options?: WorkerEntrypointExportOptions): WorkerEntrypointExport;",
			description: "Declares a WorkerEntrypoint export defined by this Worker.",
			parameterType: "WorkerEntrypointExportOptions",
			parameterOptional: true,
			children: [
				{
					name: "cache",
					type: "{ /** Whether cache is enabled for this entrypoint. */ enabled: boolean; }",
					required: false,
					description: "",
					children: [
						{
							name: "enabled",
							type: "boolean",
							required: true,
							description: "Whether cache is enabled for this entrypoint.",
							children: [],
						},
					],
				},
			],
		},
		{
			id: "Exports.workflow.default",
			name: "workflow",
			signature: "workflow(options: WorkflowExportOptions): WorkflowExport;",
			description:
				"Declares a Workflow defined by this Worker. The export's key must name a class that extends `WorkflowEntrypoint`. For more information about Workflows, see the documentation at https://developers.cloudflare.com/workflows/",
			parameterType: "WorkflowExportOptions",
			parameterOptional: false,
			children: [
				{
					name: "name",
					type: "string",
					required: true,
					description:
						"The name of the Workflow. It identifies the Workflow's instances and must be unique within the account.",
					children: [],
				},
				{
					name: "limits",
					type: "{ /** Maximum number of steps a single Workflow instance may run. */ steps?: number; }",
					required: false,
					description: "",
					children: [
						{
							name: "steps",
							type: "number",
							required: false,
							description:
								"Maximum number of steps a single Workflow instance may run.",
							children: [],
						},
					],
				},
				{
					name: "concurrency",
					type: "{ /** Maximum number of Workflow instances that can run concurrently. */ limit?: number; }",
					required: false,
					description: "",
					children: [
						{
							name: "limit",
							type: "number",
							required: false,
							description:
								"Maximum number of Workflow instances that can run concurrently.",
							children: [],
						},
					],
				},
				{
					name: "schedules",
					type: "string | string[]",
					required: false,
					description:
						"Cron schedule(s) that automatically trigger Workflow instances.",
					children: [],
				},
				{
					name: "defaultRetention",
					type: "{ /** How long to retain instances that completed successfully or were terminated. */ successRetention?: number | string; /** How long to retain errored instances. */ errorRetention?: number | string; }",
					required: false,
					description:
						'Default retention for instances of this Workflow, applied when an instance does not set its own retention. Accepts milliseconds or a duration string such as `"3 days"`.',
					children: [
						{
							name: "successRetention",
							type: "number | string",
							required: false,
							description:
								"How long to retain instances that completed successfully or were terminated.",
							children: [],
						},
						{
							name: "errorRetention",
							type: "number | string",
							required: false,
							description: "How long to retain errored instances.",
							children: [],
						},
					],
				},
			],
		},
	],
};
