// Generated by Wrangler by running `wrangler types ./worker/worker-configuration.d.ts`

interface Env {
	ASSETS: Fetcher;
}
declare module "*/_redirects" {
	const value: string;
	export default value;
}
