/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.test.json --include-runtime=false ./worker/worker-configuration.d.ts` (hash: 91843944ce7a125638f1fe490aeb5eda)
interface __BaseEnv_Env {
	MIDDLECACHE: R2Bucket;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*/__redirects" {
	const value: string;
	export default value;
}
