#! /bin/bash

repo_root_dir="$(git rev-parse --show-toplevel)"

pushd "${repo_root_dir}" > /dev/null || return

base_commit=$(git merge-base HEAD origin/production)
git diff $base_commit... --diff-filter=ACMRT --name-only | grep -E '\.(htm|html|yaml|yml|md|mdx)$' > tools/relevant_changed_files.txt || true

# this file wants to also match uncommitted changes, not just commited changes (in CI this is not the case)
git diff --diff-filter=ACMRT --name-only | grep -E '\.(htm|html|yaml|yml|md|mdx)$' >> tools/relevant_changed_files.txt || true

if [ -s tools/relevant_changed_files.txt ]; then
  list_of_files=$(cat tools/relevant_changed_files.txt | tr '\n' ' ')

  docker run --rm -v "${PWD}:/src" semgrep/semgrep \
    semgrep scan \
      --config .semgrep --metrics=off \
      --include "*.mdx" --include "*.mdx" \
      --force-color \
      $list_of_files
else
  echo "No relevant files changed."
fi

popd > /dev/null || return
