name = "workers"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true
kv-namespaces = [{ binding = "REDIRECTS", id = "1f759966503240aeb7acab72ae4e70c0", preview_id = "1f759966503240aeb7acab72ae4e70c0" }] # `workers-docs-REDIRECTS_DEV` in dash

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/workers*"
kv-namespaces = [{ binding = "REDIRECTS", id = "18460178b7c6458b9dd4f6b99b27d2b1", preview_id = "18460178b7c6458b9dd4f6b99b27d2b1" }] # `workers-docs-REDIRECTS` in dash

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
