name = "stream"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true
kv_namespaces = [
  { binding = "REDIRECTS", id = "0f8c3cc688e140c08ca2d02b45a372ed", preview_id = "0f8c3cc688e140c08ca2d02b45a372ed" }
]

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/stream*"
kv_namespaces = [
  { binding = "REDIRECTS", id = "8cb5553905824691a52f5336f6f02d12", preview_id = "8cb5553905824691a52f5336f6f02d12" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
