name = "firewall"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/firewall*"
kv_namespaces = [ 
    { binding = "REDIRECTS", id = "6405ea2c8e794feca7b5dfcc5e53875a" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
