name: Label PR Size

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pr_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install @actions/core @actions/github

      - name: Check PR Size
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'size/') }}
        run: node .github/workflow-scripts/label-pr-size.js
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'
        working-directory: ${{ github.workspace }}
