name: Flag changed filenames

# **What it does**: Adds a comment if a PR renames or removes a file.
# **Why we have it**: Highlights when we need redirects covering certain file paths.
# **Who does it impact**: PCX team, other Cloudflare contributors

on:
  pull_request:
    branches:
      - production

jobs:
  
  flag_changed_filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Renamed or Removed Files from Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub API to get list of files in the PR and filter only renamed or removed .md files
          files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | \
            jq -r '.[] | select(.status=="renamed" or .status=="removed") | select(.filename | endswith(".md")) | .filename' | \
            sed -e 's|^/content|/|' -e 's|/_index\.md$|/|' -e 's|\.md$|/|' | \
            xargs -I {} sh -c 'echo "\"{}\""' | tr '\n' ' ')
          echo "CHANGED_FILES=$files" >> "$GITHUB_ENV"

      - name: Output Changed Files
        run: echo ${{ env.CHANGED_FILES }}
