name: Flag changed filenames

# **What it does**: Adds a comment if a PR renames or removes a file.
# **Why we have it**: Highlights when we need redirects covering certain file paths.
# **Who does it impact**: PCX team, other Cloudflare contributors

on:
  pull_request:
    branches:
      - production

jobs:
  
  flag_changed_filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Renamed or Removed Files from Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub API to get list of files in the PR and filter only renamed or removed .md files
          files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | \
            jq -r '.[] | select(.status=="renamed" or .status=="removed") | select(.filename | endswith(".md")) | if .status == "renamed" then .previous_filename else .filename end' | \
            sed -e 's|^content||' -e 's|/_index\.md$|/|' -e 's|\.md$|/|' | \
            xargs -I {} sh -c 'echo "\"{}\""' | tr '\n' ' ')
          echo "CHANGED_FILES=$files" >> "$GITHUB_ENV"

      - name: Comment or Update Comment on PR if there are changed files
        if: env.CHANGED_FILES != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comment_body="This PR changes current filenames or deletes current files. Make sure you have redirects set up to cover the following paths:"
          for path in $CHANGED_FILES; do
            comment_body="$comment_body
          - [ ] $path"
          done

          existing_comment_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" | \
            jq '.[] | select(.user.id == 41898282) | select(.body | contains("This PR changes current filenames or deletes current files")) | .id')

          comment_payload=$(echo '{}' | jq --arg body "$comment_body" '.body = $body')

          if [ -z "$existing_comment_id" ]; then
            # Post a new comment
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -X POST -d "$comment_payload" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          else
            # Update the existing comment
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -X PATCH -d "$comment_payload" \
              "https://api.github.com/repos/${{ github.repository }}/issues/comments/$existing_comment_id"
          fi
