name: Holopin
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  issue_lava_lamp_holobyte:
    name: Issue Lava Lamp Holobyte
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.HOLOPIN_LABELER }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: contribution
  issue_global_contribution_badge:
    name: Issue Global Contribution badge
    runs-on: ubuntu-latest
    if: github.event.label.name == 'outstanding contribution'
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.HOLOPIN_LABELER }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: "[automation] outstanding contribution"
