name: File Check

on:
  push:
    branches:
      - production
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  file-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Unused Files
        id: find-files
        run: |
          # Find all .png and .svg files, excluding those in the ./static directory
          FILES=$(find . -type f \( -name "*.png" -o -name "*.svg" \) -not -path "./static/*")
          
          # Check if files are referenced in any markdown file
          UNUSED_FILES=""
          for FILE in $FILES; do
            FILENAME=$(basename "$FILE")
            if ! grep -q -r -F --exclude-dir=.github "$FILENAME" --include="*.md" .; then
              UNUSED_FILES+="$FILE\n"
            fi
          done
          
          # If there are unused files, output them
          if [ -n "$UNUSED_FILES" ]; then
            echo "::set-output name=unused_files::$UNUSED_FILES"
          fi

      - name: Create Issue if Unused Files Found
        if: steps.find-files.outputs.unused_files
        uses: peter-evans/create-issue@v3
        with:
          title: Unused Files Found
          body: |
            The following files are not referenced in any markdown file:

            <ul>
            ${{ steps.find-files.outputs.unused_files }}
            </ul>
