on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 4 * * *"
  pull_request: {}

name: Semgrep config
permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_URL: https://cloudflare.semgrep.dev
      SEMGREP_APP_URL: https://cloudflare.semgrep.dev
      SEMGREP_VERSION_CHECK_URL: https://cloudflare.semgrep.dev/api/check-version
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      # Semgrep CI to run on Schedule (Cron) or Manual Dispatch
      # scans using managed rules at cloudflare.semgrep.dev
      - name: Semgrep CI (Managed at cloudflare.semgrep.dev)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: semgrep ci

      # Semgrep Scan to run on Pull Request events
      # scans using rules inside the .semgrep/ folder and fails on error
      - name: Semgrep Local (Custom rules found in .semgrep)
        if: github.event_name == 'pull_request'
        # add '--error' below to return error code to workflow
        run: semgrep scan --config .semgrep --include "*.mdx" --include "*.mdx"
