name: Show Changed Files
on:
   issue_comment:
    types:
      - created
      - edited

jobs:
  changed-files-links:
    name: Show Changed Files
    if: github.event.issue.pull_request && (github.event.comment.user.id == 73139402 && contains(github.event.comment.body, 'Deploy successful')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/show-changed-files
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    continue-on-error: true
