name: Show Changed Files
on:
  pull_request:
    branches:
      - production

jobs:
  changed-files-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/show-changed-files
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    continue-on-error: true
