name: Show Changed Files
on:
  pull_request:
    branches:
      - production

jobs:
  changed-files-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install Dependencies
        run: npm install @actions/core @actions/github

      - name: Execute comment-on-pr.js
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/workflow-scripts/show-changed-files.js
        continue-on-error: true
