name: Show Changed Files

# **What it does**: Comments on a PR with before/after links for changes in the PR.
# **Why we have it**: Makes reviewing a PR much easier b/c you don't have to hunt for specific pages.
# **Who does it impact**: PCX team

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  changed-files-links:
    name: Show Changed Files
    if: github.event.issue.pull_request && github.event.issue.state == 'open' && github.event.comment.user.id == 73139402 && contains(github.event.comment.body, 'Deploy successful')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/show-changed-files
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    continue-on-error: true
