name: 🎉 Spellchecker

on: [pull_request]

jobs:
  misspell:
    name: 🧹 Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: 🍄 Check Out
        uses: actions/checkout@v2
      - name: 🥑 Install
        run: |
          wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: 🍊 Misspell
        run: |
          find products README.md -not -path 'products/api/src/content/static/css/font-awesome.min.css' -type f | xargs ./misspell -error
