name = "registrar"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true
kv-namespaces = [{ binding = "REDIRECTS", id = "a08297023fa44f369c9828b0e7674960", preview_id = "a08297023fa44f369c9828b0e7674960" }]

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/registrar*"
kv-namespaces = [{ binding = "REDIRECTS", id = "4d1bd48761af4841bc13905dd9d5969d", preview_id = "4d1bd48761af4841bc13905dd9d5969d" }]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
